### ISSUE TITLE
Resolve duplicate photos from article pages

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-citylimits#124]
Programatically remove the article image that's in the top of the content area. 

In the rare case when then featured image and the top image are different, it's fine to supplant the top image with the featured image.

**Comment by benlk** [comment]
This is what we'd need to remove to fix the problem: https://github.com/INN/umbrella-citylimits/blob/master/wp-content/themes/citylimits/inc/post-templates.php

Are we worried about historic content?

**Comment by benlk** [comment]
That doesn't actually fix the problem, it turns out. The real cause of the duplicate image was because when I created `single-two-column.php` for #99, I included `largo_hero( null,'' );` from Largo's template. Since https://github.com/INN/umbrella-citylimits/pull/5, City Limits had been using versions of the single-column and double-column templates that did not output the image.
