### ISSUE TITLE
Homepage: Ad widget areas

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-citylimits#44]
- Create custom widget areas for Ads/CTAs on homepage based on approved design
- Styling with gray/beige background

**Comment by benlk** [comment]
@MirandaEcho do we know if they're using https://wordpress.org/plugins/doubleclick-for-wp/ for this purpose, or if they want to use some custom ad widget?

**Comment by MirandaEcho** [comment]
Ads will be inserted with Super Cool Ad inserter plugin

**Comment by benlk** [comment]
Super Cool Ad Inserter Plugin does not provide widgets to insert ads; it provides widget areas in articles where widgets may be placed.

Did you mean the Super Cool Ad Manager Plugin, which provides Google Ad Manager ads as widgets?

**Comment by MirandaEcho** [comment]
I'm not understanding your question, then.  Let's discuss.

**Comment by benlk** [comment]
If they want us to set up the Google Ad Manager widgets using SCAMP on staging, we'll need to either have access to their GAM admin, or we'll need to know what the ad codes for the ad units they want to run are, and what resolutions those ad codes will support.

**Comment by benlk** [comment]
We're aiming for this:

<img width="559" alt="Screen Shot 2019-10-22 at 14 38 43 " src="https://user-images.githubusercontent.com/1754187/67318569-aa138f80-f4d9-11e9-8245-6fbac0f350d5.png">

SCAMP's built-in styles include a `::before` element that provides the "Advertisement" text above the image. Is it alright if we keep that text above, rather than beneath?

Here's an example of how it displays in the middle of post content at https://therivardreport.com/new-wood-construction-mid-rise-on-broadway-bucks-building-trends/ :
![Screen Shot 2019-10-22 at 14 38 06 ](https://user-images.githubusercontent.com/1754187/67318699-d5967a00-f4d9-11e9-8183-18b10ccaf7cb.png)

**Comment by MirandaEcho** [comment]
@benlk - yes, the advertisement text above is fine

**Comment by benlk** [comment]
Ads discovered by reviewing the widgets used on the site so far:

- `Full300by600Slot1` at 300x600 in all device breakpoints on https://citylimits.org/series/beyond-promises-bloomberg-and-homelessness  and in the archive sidebar
- `Homepage_Ad_Slot1_300x250` at 300x250 in all breakpoints, but in the "Events" sidebar and not on the homepage

I don't see any others in the widgets.

**Comment by kaylima** [comment]
@MirandaEcho and @benlk I think something was lost in translation here... we need ads in posts using SCAIP ... AND ALSO ads on the homepage, etc. From what I can tell, there hasn't been any styling done for the ad at the very top of the page (above the logo), or between sections of the homepage. Is that true? We need that done ASAP, if so.
