### ISSUE TITLE
Newsletter Widget Area

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-citylimits#49]
- Expand on hover functionality on desktop 
    - Existing Newsletter build, but with new styling!
    - On mobile, click to expand

**Comment by joshdarby** [comment]
Hopefully we can just rework the existing newsletter sign up block.

But we'll also need to remember to account for success and error states after submit.

**Comment by benlk** [comment]
click-to-expand/hover-to-expand functionality already exists; we're just changing the styling and presentation of the existing forms.

![Screen Shot 2019-10-21 at 10 40 44 ](https://user-images.githubusercontent.com/1754187/67215330-44e36f80-f3ef-11e9-8934-69277acda1b0.png)

The existing forms have a selector whereby users can choose which newsletter they sign up for. Is this going away? If so, which newsletter will people be signed up for?

**Comment by joshdarby** [comment]
@benlk There are multiple newsletter subscription options in the new design

![Screen Shot 2019-10-21 at 10 42 07 AM](https://user-images.githubusercontent.com/18353636/67215451-7bb98580-f3ef-11e9-95da-f4a71dcd7132.png)

**Comment by kaylima** [comment]
@ben and @joshdarby we should only rework the styling of the existing one and not make any changes to the fields or back-end

**Comment by benlk** [comment]
Some of the mobile mockups didn't show the checkboxes, but we can easily include them.

<img width="278" alt="Screen Shot 2019-10-21 at 15 38 19 " src="https://user-images.githubusercontent.com/1754187/67237217-d74c3900-f418-11e9-8790-460bb67f0127.png">

**Comment by MirandaEcho** [comment]
There's an FYI from Kay in #38

**Comment by benlk** [comment]
> NOTE FOR DEVELOPMENT:
> 
> let's explore the Jetpack feature for hiding widgets when we set up the pre-footer area for the newsletter signup (specifically for articles/posts)

**Comment by benlk** [comment]
The existing newsletter signup forms:

![Screen Shot 2019-11-12 at 14 26 58 ](https://user-images.githubusercontent.com/1754187/68703453-b202a480-0558-11ea-88f2-fceafc27133b.png)

1. The "CL Newsletter Link for Header" widget, which has no options and is basically a fancy link to `/newsletter-subscriptions/` (see https://citylimits.org/newsletter-subscriptions/)
2. `partials/newsletter-signup-maincolumn.php`, which is added via an action to 'largo_before_sticky_posts', 'largo_category_after_primary_featured_post', 'largo_series_before_stories', and 'largo_archive_before_stories'
3. `partials/newsletter-signup-footer.php`, which is added via an action to 'largo_before_footer'. If we want to control the visibility of this via Jetpack's options, we will need to convert this to a widget for the Footer widget area (said area needs to be enabled as in https://github.com/INN/umbrella-citylimits/issues/76) so that we can use the Jetpack widget visibility controls.

Also on the site are:
1. The popover, which is `partials/newsletter-signup-popover.php` and added as an action to 'wp_footer'
2. The shortcode `[cl-newsletter]`, which uses `partials/newsletter-signup-maincolumn.php`
3. The https://citylimits.org/newsletter-subscriptions/ page, which uses the `page-newsletter-signup-subscriptions.php` template, and whose options are configured via ACF on that page. 

Here's that page:

![Screen Shot 2019-11-12 at 14 42 56 ](https://user-images.githubusercontent.com/1754187/68704713-bdef6600-055a-11ea-98e1-d6e6cbe82a94.png)


Todo list:

- [ ] revise styles for 
    - [ ] newsletter-signup-footer.php
    - [ ] newsletter-signup-header.php
    - [ ] newsletter-signup-maincolumn.php
    - [ ] newsletter-signup-popover.php

Questions for @kaylima:
- [ ] Should we make the existing header widget have an option to choose the partial that is output, so that it can be used in more places? @kaylima you had said this should only address visuals, not backend changes.
- [ ] There are no mockups that directly address the newsletter signup page; how should it be addressed?

**Comment by benlk** [comment]
Notes:
- not updating anything on the Newsletter Signup page, even the styles specific to that page
- getting rid of newsletter-signup-footer.php and newsletter-signup-header.php
- change the widget to use the "maincolumn" 
- unexpanded state should be black with white text, dropping the existing logo SVG
- there's a bug where expanding, then collapsing the form puts it in a state where it may never open again, until the page is refreshed.

**Comment by benlk** [comment]
Are we at all concerned about the OptinMonster popup? It's the foreground one in this screenshot, and styling appears to be entirely controlled via an OptinMonster account and the app.optinmonster.com dashboard:

![Screen Shot 2019-11-12 at 17 58 18 ](https://user-images.githubusercontent.com/1754187/68717977-0f591e80-0576-11ea-8c35-b0c7ef3dcf49.png)

**Comment by benlk** [comment]
In work for this PR, I'm constraining the width of the footer skyline image to 1170px so that it matches the width of the newsletter signup box:

Before:
![Screen Shot 2019-11-12 at 21 15 49 ](https://user-images.githubusercontent.com/1754187/68727227-cfa03000-0591-11ea-9bb5-6d6b0e9a1868.png)

After:
![Screen Shot 2019-11-12 at 21 14 29 ](https://user-images.githubusercontent.com/1754187/68727232-d464e400-0591-11ea-97c9-384786a3f45c.png)

**Comment by benlk** [comment]
Also, can we shave off this tiny spire?

![Screen Shot 2019-11-12 at 21 17 41 ](https://user-images.githubusercontent.com/1754187/68727273-ec3c6800-0591-11ea-9873-59edcb53f01c.png)
