### ISSUE TITLE
Drop cap styling

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-citylimits#56]

**Comment by benlk** [comment]
We won't be modifying the markup, but https://product.voxmedia.com/2019/6/17/18524029/the-ballad-of-drop-caps-and-design-systems has some nice style implementation inspiration.

**Comment by kaylima** [comment]
Neue Haas Grotesk Text Pro 75 Bold, black

**Comment by benlk** [comment]
`city-limits-screens.13.xd` shows the drop cap as being offset up and to the left from the bounding box of the containing paragraph. Is that intended? Or is that a side effect of me not having the fonts installed because I don't have a paid Creative Cloud subscription that will enable me to use Adobe Fonts on my computer?

**Comment by benlk** [comment]
#109 uses this arrangement:

![Screen Shot 2019-11-11 at 21 26 45 ](https://user-images.githubusercontent.com/1754187/68689959-38aa8800-053f-11ea-8687-8db14c93474e.png)
