### ISSUE TITLE
Special projects: featured content area

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-citylimits#73]
- Posts
- One with image and excerpt
- Two below only headline and byline
- More button

**Comment by benlk** [comment]
Where on the mockup is this section?

**Comment by joshdarby** [comment]
@benlk I think it's this section?

![Screen Shot 2019-10-21 at 12 40 50 PM](https://user-images.githubusercontent.com/18353636/67224817-0b673000-f400-11e9-991e-46097f2925de.png)

**Comment by benlk** [comment]
What makes this section "featured content" relative to the "latest news" section at the top of the page in #70? Is it basically just the main archive loop for the rest of the posts in this section, or is it supposed to be filtered somehow?

**Comment by kaylima** [comment]
@miranda please confirm and provide screenshot of this section

**Comment by MirandaEcho** [comment]
That screenshot is correct. They'd like to have it be an archive of the rest of the stories in that project, avoiding duplication from previous content areas if possible.

As with the rest of the special project content areas, it will be an optional area so they can exclude it for newer projects with limited content.

**Comment by benlk** [comment]
>  it will be an optional area so they can exclude it for newer projects with limited content.

I was thinking this was a fixed part of the template, for easier Load More Posts integration. Largo's Load More Posts functionality wasn't built with more than one button on the page in mind, so I'm not sure what might happen if they put more than one widget built with Largo's LMP on the page. 

Potential resolutions:
- We could have it query `-1` (infinite) posts to avoid having to use Largo's LMP or other paginators
- Include text saying "don't use more than one of these on the page"
- Build a custom LMP solution that lets them put more than one on the page
- In the widget with the LMP solution, don't include any category-choice option, so that the widget can only be used to cover the series that is on the page, so that there's no real reason to have two of the same widget on the page because they'd display the same things
- Just use Largo Recent Posts or one of the other widgets from this SOW, and make sure it looks good in this section. Provide no LMP. Let them increase the count until they run of posts.

**Comment by benlk** [comment]
(pending client feedback on how they want to handle archives for special projects)

**Comment by joshdarby** [comment]
@MirandaEcho Question about the ordering of these:

Is this the correct order that the posts should be in?
![Screen Shot 2019-11-07 at 11 59 16 AM](https://user-images.githubusercontent.com/18353636/68410209-5f8b4780-0156-11ea-964c-61593959d1fd.png)

Or should be like this? If it's supposed to be like this, where are these 2nd row of posts coming from?
![Screen Shot 2019-11-07 at 12 00 24 PM](https://user-images.githubusercontent.com/18353636/68410240-6e71fa00-0156-11ea-93fe-e193fdc58f8a.png)

**Comment by MirandaEcho** [comment]
@joshdarby  the first one works for me
